// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfr-dp7OcWAS5CwB_bAoPzhD2J6MQMjAA',
    appId: '1:225981944136:web:3aa0fd7c37cbd0b405637d',
    messagingSenderId: '225981944136',
    projectId: 'bruckefamilia',
    authDomain: 'bruckefamilia.firebaseapp.com',
    storageBucket: 'bruckefamilia.firebasestorage.app',
    measurementId: 'G-PN82XZECFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo4hT_X3yi91KkyIlqbv2VNou1DC7hDc4',
    appId: '1:225981944136:android:785043ac14b1d6db05637d',
    messagingSenderId: '225981944136',
    projectId: 'bruckefamilia',
    storageBucket: 'bruckefamilia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWMhwASpgnkgc8v1simKe8qv4FY0SvBg',
    appId: '1:225981944136:ios:322fdf1307a8acd005637d',
    messagingSenderId: '225981944136',
    projectId: 'bruckefamilia',
    storageBucket: 'bruckefamilia.firebasestorage.app',
    iosBundleId: 'com.arxforense.bruckefamilia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqWMhwASpgnkgc8v1simKe8qv4FY0SvBg',
    appId: '1:225981944136:ios:322fdf1307a8acd005637d',
    messagingSenderId: '225981944136',
    projectId: 'bruckefamilia',
    storageBucket: 'bruckefamilia.firebasestorage.app',
    iosBundleId: 'com.arxforense.bruckefamilia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfr-dp7OcWAS5CwB_bAoPzhD2J6MQMjAA',
    appId: '1:225981944136:web:3c086bc488b1dae805637d',
    messagingSenderId: '225981944136',
    projectId: 'bruckefamilia',
    authDomain: 'bruckefamilia.firebaseapp.com',
    storageBucket: 'bruckefamilia.firebasestorage.app',
    measurementId: 'G-H4P2DKMXY1',
  );
}
